[build]
  command = "npm run build"
  publish = "dist"
  base = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "3.2.2"
  GO_VERSION = "1.21"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = "dist"
  base = "."

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
  base = "." 